version: '3'

services:
  db:
    image: mariadb:10.3.39
    env_file:
      - path: ./.env
        required: true
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  mariadb-data:
