on:
  push:
    branches: [master, main, test]
name: 🚀 Deploy website on push to master
jobs:
  upload-static-assets:
    name: Upload static assets
    runs-on: ubuntu:-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync public files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOSTNAME }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./apps/site/public/
          dry-run: false

  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Create build
        run: pnpm run build --filter=site

      - name: Move static files
        shell: bash
        run: |
          mv ./apps/site/dist/static/* ./apps/site/dist/standalone/apps/site/

      - name: 📂 Sync server files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOSTNAME }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./apps/site/dist/standalone/apps/site/
          dry-run: false

      - name: Create file to restart server
        shell: bash
        run: touch ./tmp/restart.txt


      # When dependencies have changed, manual install is needed...